name: ros-talker-listener
version: '0.1'
summary: ROS Talker/Listener Example
description: |
  This example launches a ROS talker and listener.

confinement: devmode
base: core20

parts:
  ros-tutorials:
    plugin: catkin
    source: https://github.com/ros/ros_tutorials.git
    source-branch: noetic-devel
    catkin-packages: [roscpp_tutorials]
    stage-packages:
        - ros-noetic-roslaunch

apps:
  ros-talker-listener:
    command: opt/ros/noetic/bin/roslaunch roscpp_tutorials talker_listener.launch
    extensions: [ros1-noetic]
